#Test with: http://editor.swagger.io/

swagger: "2.0"
info:
    version: 1.0.0
    title: Microservice for Interactions
    description: C# + PostgreSQL
    license:
        name: phets-interaction-ms
host: localhost:4005
basePath: /
schemes:
    - http
consumes:
    - application/json
produces:
    - application/json
paths:
    /api/interaction/Match:
        get:
            summary: Returns true if there is a match between two users, false otherwise
            operationId: verifyMatchState
            parameters:
                - name: id_main
                  in: query
                  description: The id of user1
                  required: true
                  type: integer
                - name: id_secondary
                  in: query
                  description: The id of user2
                  required: true
                  type: integer
            responses:
                "200":
                    description: Success
                "500":
                    description: Bad Request

    /api/interaction/Unlike:
        put:
            summary: Unlikes a user with a given id after it was liked
            operationId: unlikeUser
            parameters:
                - name: id_main
                  in: query
                  description: The id of the user that makes the interaction
                  required: true
                  type: integer
                - name: id_secondary
                  in: query
                  description: The id of the user that the interaction is going to be made with
                  required: true
                  type: integer
            responses:
                "200":
                    description: Success
                "500":
                    description: Bad Request

    /api/interaction/Create:
        post:
            summary: Creates an interaction between two users
            operationId: createInteraction
            parameters:
                - name: id_main
                  in: query
                  description: The id of the user that makes the interaction
                  required: true
                  type: integer
                - name: id_secondary
                  in: query
                  description: The id of the user that the interaction is going to be made with
                  required: true
                  type: integer
                - name: match_1
                  in: query
                  description: State of the interaction
                  required: true
                  type: bool
            responses:
                "200":
                    description: Success
                "500":
                    description: Bad Request

definitions:
    # Users
    Interaction:
        type: object
        properties:
            Id:
                type: integer
            IdMain:
                type: integer
            IdSecondary:
                type: integet
            Match_1:
                type: bool
            Match_2:
                type: bool

    Match:
        type: object
        properties:
            State:
                type: bool
